## Customer Retention & Cohort Analysis – SQL Queries

### Database Setup

```sql
CREATE DATABASE project1;
USE project1;
```

### Rename Tables for Readability

```sql
ALTER TABLE olist_customers_dataset RENAME customers;
ALTER TABLE olist_order_items_dataset RENAME order_items;
ALTER TABLE olist_order_payments_dataset RENAME payments;
ALTER TABLE olist_orders_dataset RENAME orders;
```

---

# Exploratory Data Analysis (EDA)

## Total Orders

```sql
SELECT COUNT(*) AS total_orders
FROM orders;
```

Displays the overall transaction volume (~100K orders), confirming sufficient data for customer behavior analysis.

---

## Total Customers

```sql
SELECT COUNT(DISTINCT customer_unique_id)
FROM customers;
```

Shows the number of unique customers in the dataset.

---

## Orders by Status

```sql
SELECT order_status, COUNT(*) AS total_orders
FROM orders
GROUP BY order_status
ORDER BY total_orders DESC;
```

Helps identify operational performance such as delivered, cancelled, or unavailable orders.

---

## Monthly Orders Trend

```sql
SELECT
DATE_FORMAT(order_purchase_timestamp,'%Y-%m') AS order_month,
COUNT(*) AS number_of_orders
FROM orders
GROUP BY order_month
ORDER BY order_month;
```

Shows seasonal demand patterns, with order volume increasing toward the end of the year.

---

## Total Revenue

```sql
SELECT ROUND(SUM(payment_value),2) AS total_payments
FROM payments;
```

Provides an overview of total revenue generated on the platform.

---

# Customer Purchase Analysis

## Orders per Customer

```sql
SELECT c.customer_unique_id,
COUNT(o.order_id) AS orders_placed
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY orders_placed DESC
LIMIT 10;
```

Identifies customers with the highest order counts.

---

## Average Orders per Customer

```sql
SELECT
ROUND(COUNT(o.order_id) / COUNT(DISTINCT c.customer_unique_id),2)
AS avg_orders_per_customer
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id;
```

Measures how frequently customers return to make purchases.

---

## Distribution of Customers by Order Count

```sql
WITH cte AS (
SELECT c.customer_unique_id,
COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
)

SELECT total_orders,
COUNT(*) AS number_of_customers
FROM cte
GROUP BY total_orders
ORDER BY total_orders;
```

Highlights customer retention patterns across order frequency.

---

## Repeat Customer Rate

```sql
WITH cte AS(
SELECT c.customer_unique_id,
COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
)

SELECT
SUM(CASE WHEN total_orders > 1 THEN 1 ELSE 0 END) * 100 / COUNT(*)
AS repeat_customer_rate
FROM cte;
```

Measures the percentage of customers who placed more than one order.

---

## Monthly New Customers

```sql
WITH cte AS (
SELECT c.customer_unique_id,
MIN(o.order_purchase_timestamp) AS first_purchase_date
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
)

SELECT
DATE_FORMAT(first_purchase_date,'%Y-%m') AS month,
COUNT(DISTINCT customer_unique_id) AS new_customers
FROM cte
GROUP BY month
ORDER BY month;
```

Tracks customer acquisition growth over time.

---

# High Value Customer Analysis

## Top 10 Customers by Revenue

```sql
SELECT
c.customer_unique_id,
COUNT(o.order_id) AS total_orders,
SUM(p.payment_value) AS total_payment,
SUM(p.payment_value) * 100 /
(SELECT SUM(payment_value) FROM payments)
AS revenue_percentage
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments p ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
ORDER BY total_payment DESC
LIMIT 10;
```

Identifies the highest value customers and their revenue contribution.

---

## Revenue Generated by Top 10 Customers

```sql
WITH cte AS(
SELECT c.customer_unique_id,
SUM(p.payment_value) AS total_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments p ON p.order_id = o.order_id
GROUP BY c.customer_unique_id
)

SELECT customer_unique_id,
total_revenue
FROM cte
ORDER BY total_revenue DESC
LIMIT 10;
```

---

## Revenue Contribution of Top 25,000 Customers

```sql
WITH cte AS(
SELECT c.customer_unique_id,
SUM(p.payment_value) AS total_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments p ON o.order_id = p.order_id
GROUP BY c.customer_unique_id
)

SELECT
ROUND(SUM(total_revenue),2) AS revenue_top_25000,
ROUND(
SUM(total_revenue) * 100 /
(SELECT SUM(total_revenue) FROM cte),2
) AS revenue_percentage
FROM (
SELECT total_revenue
FROM cte
ORDER BY total_revenue DESC
LIMIT 25000
)t;
```

Shows that the **top 25K customers contribute ~60% of total revenue**, indicating revenue concentration.

---

# Loyal Customer Identification

```sql
SELECT
c.customer_unique_id,
COUNT(o.order_id) AS number_of_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
HAVING COUNT(o.order_id) > 3
ORDER BY number_of_orders DESC;
```

Identifies highly loyal customers with multiple purchases.

---

# Cohort Retention Analysis

## First Purchase per Customer (Cohort Identification)

```sql
WITH cte1 AS(
SELECT
c.customer_unique_id,
MIN(o.order_purchase_timestamp) AS first_purchase
FROM orders o
JOIN customers c
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
)

SELECT *
FROM cte1;
```

Determines when each customer entered the platform.

---

## Assign Customers to Cohorts

```sql
WITH cte1 AS (
SELECT
c.customer_unique_id,
MIN(o.order_purchase_timestamp) AS first_purchase
FROM orders o
JOIN customers c
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
)

SELECT
customer_unique_id,
DATE_FORMAT(first_purchase,'%Y-%m') AS cohort_month
FROM cte1;
```

---

## Cohort Retention Table

```sql
WITH cte1 AS(
SELECT c.customer_unique_id,
MIN(o.order_purchase_timestamp) AS first_order
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
),

cte2 AS (
SELECT
c.customer_unique_id,
DATE_FORMAT(c1.first_order,'%Y-%m') AS cohort_month,
TIMESTAMPDIFF(
MONTH,
c1.first_order,
o.order_purchase_timestamp
) AS month_number
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN cte1 c1
ON c1.customer_unique_id = c.customer_unique_id
)

SELECT
cohort_month,
month_number,
COUNT(DISTINCT customer_unique_id) AS retained_customers
FROM cte2
GROUP BY cohort_month, month_number
ORDER BY cohort_month, month_number;
```

Shows retention decline after the first purchase month.

---

# Customer Lifetime Value (CLTV)

## CLTV Table

```sql
SELECT
c.customer_unique_id,
COUNT(DISTINCT o.order_id) AS total_orders,
SUM(p.payment_value) AS lifetime_revenue,
ROUND(SUM(p.payment_value) /
COUNT(DISTINCT o.order_id),2) AS average_order_value
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN payments p ON p.order_id = o.order_id
GROUP BY c.customer_unique_id
ORDER BY lifetime_revenue DESC;
```

Highlights revenue generated by each customer over their lifetime.

---

## Average Customer Lifetime Value

```sql
WITH cte AS(
SELECT
c.customer_unique_id,
SUM(p.payment_value) AS revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON p.order_id = o.order_id
GROUP BY c.customer_unique_id
)

SELECT
ROUND(AVG(revenue),2) AS average_cltv
FROM cte;
```

---

# Customer Revenue Ranking

```sql
SELECT
c.customer_unique_id,
SUM(p.payment_value) AS lifetime_value,
DENSE_RANK() OVER(
ORDER BY SUM(p.payment_value) DESC
) AS ranking
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_unique_id;
```

Ranks customers based on total revenue contribution.
