use project1;

-- Total Customers vs Customers Who Placed Orders
select count(distinct c.customer_unique_id) as total_customers, 
count(distinct o.customer_id) as customers_with_orders,
round(count(distinct c.customer_unique_id)*100/count(distinct o.customer_id),2) as activation_rate
from customers c left join orders o 
on c.customer_id=o.customer_id;
-- Approximately 96.6% of registered customers placed at least one order, indicating strong initial 
-- conversion from registration to purchase.
-- --------------------------------------------------------------------------------------------------------------------

-- Order Status Funnel
select order_status, count(*) as total_orders, 
count(*)*100/ (select count(order_id) from orders) as order_as_percentage_of_total
from orders
group by order_status
order by total_orders desc;
-- Over 96% of orders were successfully delivered, indicating strong fulfillment performance.
-- Only a small proportion of orders were cancelled or unavailable (<2%), suggesting efficient logistics operations.
-- ------------------------------------------------------------------------------------------------------------------

-- Repeat customers and number of orders placed by them
with cte as
(
select c.customer_unique_id,
count(o.order_id) as number_of_orders
from customers c join orders o
on c.customer_id=o.customer_id
group by c.customer_unique_id
)
select customer_unique_id, number_of_orders
from cte
where number_of_orders>1
group by customer_unique_id
order by number_of_orders desc;
-- ------------------------------------------------------------------------------------------------------------------

-- Repeat customer rate
with cte as(
select c.customer_unique_id, count(o.order_id) as total_orders
from customers c join orders o
on c.customer_id=o.customer_id
group by c.customer_unique_id
)
select sum(case when total_orders>1 then 1 else 0 end)*100/count(*) as repeat_customer_rate
from cte;
-- Only ~3% of customers made repeat purchases, indicating low customer retention.
-- Improving repeat purchase behavior could significantly increase customer lifetime value.
-- ------------------------------------------------------------------------------------------------------------------

-- Average Time Between Order Purchase and Delivery
select round(avg(datediff(order_delivered_customer_date, order_purchase_timestamp)),2) as avg_delivery_time
from orders
where order_status='delivered';
-- The average delivery time is approximately 12 days, which reflects the logistics performance of the platform.
-- ------------------------------------------------------------------------------------------------------------------

-- Monthly Order Conversion Trend
select date_format(order_purchase_timestamp, '%Y-%m') as month, count(order_id) as number_of_orders
from orders
group by date_format(order_purchase_timestamp, '%Y-%m')
order by month;
-- The number of monthly orders increased significantly between 2017 and 2018, indicating strong growth in 
-- platform adoption.
-- ------------------------------------------------------------------------------------------------------------------

-- Average Order Value (AOV)
select round(sum(payment_value)/count(distinct order_id),2) as average_order_value
from payments;
-- The average order value is approximately R$160, indicating that most purchases fall within a moderate price range 
-- typical of everyday consumer goods.
-- ------------------------------------------------------------------------------------------------------------------

-- Total Revenue Generated by the Platform
select round(sum(payment_value),2) as total_revenue
from payments;
-- The platform generated approximately R$16 million in total transaction revenue, demonstrating substantial 
-- marketplace activity.
-- ------------------------------------------------------------------------------------------------------------------

-- Top 10 Revenue Generating Customers
with cte as 
(select c.customer_unique_id,sum(p.payment_value) as total_revenue
from customers c join orders o
on c.customer_id=o.customer_id
join payments p
on p.order_id=o.order_id
group by c.customer_unique_id
order by total_revenue desc)
select customer_unique_id, total_revenue
from cte
order by total_revenue desc
limit 10;
-- The highest-value customer generated over R$13K in revenue, significantly exceeding the platform's average 
-- customer value.
-- ------------------------------------------------------------------------------------------------------------------

-- Revenue Contribution of Top 5% Customers
with cte as 
(
select c.customer_unique_id, sum(p.payment_value) as revenue
from customers c join orders o
on c.customer_id=o.customer_id
join payments p
on p.order_id=o.order_id
group by c.customer_unique_id
),
cte2 as
(
select customer_unique_id, revenue, 
ntile(20) over(order by  revenue desc) as percentile
from cte
)
select round(sum(case when percentile=1 then revenue end)*100/sum(revenue),2) as revenue_share_top_5_percent
from cte2;
-- Top 5% customers generate ~30% of revenue
-- A small segment of customers contributes a disproportionately large share of revenue.
-- ------------------------------------------------------------------------------------------------------------------

-- Average Number of Orders per Customer
select round(count(distinct o.order_id)/count(distinct c.customer_unique_id),2) as aov
from customers c join orders o
on c.customer_id=o.customer_id
join payments p
on o.order_id=p.order_id;
-- The average customer places only slightly more than one order, confirming low repeat purchase behavior.
-- ------------------------------------------------------------------------------------------------------------------

-- Monthly Revenue Trend
select date_format(o.order_purchase_timestamp,'%Y-%m') as month, round(sum(p.payment_value),2) as revenue
from orders o join payments p
on o.order_id=p.order_id
group by date_format(o.order_purchase_timestamp,'%Y-%m')
order by month;
-- Revenue steadily increases during 2017–2018.
-- Monthly revenue shows consistent growth, suggesting increasing platform adoption over time.
-- ------------------------------------------------------------------------------------------------------------------

-- Delivery Success Rate
-- percentage of orders that were delivered sucessfully
select count(case when order_status='delivered' then 1 end)*100/count(order_id) as successfull_delivery_percentage
from orders;
-- The platform achieves a high delivery success rate, indicating efficient order fulfillment and logistics 
-- operations.
-- ------------------------------------------------------------------------------------------------------------------


